### PR TITLE
make some dark theme changes

### PR DESCRIPTION
**Pull request by FredKSchott**
I found the "bright white" on "dark black" color theme a bit harsh on the eyes. This lights the background color a bit, and is now closer to VSCode than what we had before. It also fixes a few color bugs in dark mode, that I found while poking around.

## Before

Screen Shot 2021-07-13 at 3 27 20 PM

## After

Screen Shot 2021-07-13 at 3 27 19 PM

### CODE REVIEW

**Comment by jasikpark** [comment]
Aww I really love the dark inky black of space. 😆 That's understandable though.

Could you check out the color changes with https://addons.mozilla.org/en-US/firefox/addon/axe-devtools/ or https://chrome.google.com/webstore/detail/axe/lhdoppojpmngadmnindnejefpokejbdd just to double-check that the contrast is still high enough?

**Comment by jasikpark** [comment]
The subdued theme is pretty, but I think the body text might be a little too low contrast? I find it hard to read with a reflection on my screen.e

**Comment by itskitto** [comment]
> The subdued theme is pretty, but I think the body text might be a little too low contrast? I find it hard to read with a reflection on my screen.e

Yeah I think the contrast may need a adjusting as well but overall this dark theme is MUCH easier on the eyes. I have severe, and I mean SEVERE astigmatism and the original dark mode was a bit difficult at times.

**Comment by jasikpark** [comment]
Maybe we could bring back the ultradark theme someday as an extra fancy theme switcher xD

**Comment by FredKSchott** [comment]
Konami code ultra dark theme?

**Comment by FredKSchott** [comment]
I tested the body text as AA accessibility compliant, but that’s a good call to check the rest of the site

**Comment by jasikpark** [comment]
It looks like there's some problems with the body text color when on the blockquote background, for example

**Comment by FredKSchott** [comment]
Good catch, fixed!

I'm going to try to merge this sooner, and happy to keep fiddling with colors before release

**Pull request merged**
