### PR TITLE
quick-start page

### PR DESCRIPTION
**Pull request by jgil-r**
Added content to quick-start page. Let me know if their is other information that should be added.

### CODE REVIEW

**Comment by Hanawa02** [comment]
Looks fine to me.

I'll just add an issue to merge the quick start with the installation later since it seems to me that there is a lot of overlapping content.

**Comment by Hanawa02** [comment]
@FredKSchott we have some issues with the deployment here, maybe we could switch off the deployments for PR for now and leave just the deployment for the main?

**Comment by jgil-r** [comment]
> Looks fine to me.
> 
> I'll just add an issue to merge the quick start with the installation later since it seems to me that there is a lot of overlapping content.

Yeah I noticed there is a lot of similar information in the home,  /installation, and /quickstart page. Also, would making the docs sidebar headings just be headings instead of links with their own page better? Might help avoid repetitive information.

**Comment by itskitto** [comment]
> 
> 
> @FredKSchott we have some issues with the deployment here, maybe we could switch off the deployments for PR for now and leave just the deployment for the main?

I think deployments for PRs are helpful when you want to see the physical changes the PR is making to the website

**Pull request merged**
